export enum AlertType {
  TAB_SWITCH = 'TAB_SWITCH',
  WINDOW_BLUR = 'WINDOW_BLUR',
  FULLSCREEN_EXIT = 'FULLSCREEN_EXIT',
  FACE_NOT_DETECTED = 'FACE_NOT_DETECTED',
  MULTIPLE_FACES = 'MULTIPLE_FACES',
  FACE_MISMATCH = 'FACE_MISMATCH',
  LIVENESS_FAILED = 'LIVENESS_FAILED',
  COPY_PASTE_ATTEMPT = 'COPY_PASTE_ATTEMPT',
  SECOND_SCREEN = 'SECOND_SCREEN',
  CONNECTION_LOST = 'CONNECTION_LOST',
  BROWSER_CLOSED = 'BROWSER_CLOSED',
}
