export enum CustomSessionStatus {
  PENDING = 'PENDING',
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
  EXPIRED = 'EXPIRED',
  DISQUALIFIED = 'DISQUALIFIED',
  CANCELLED = 'CANCELLED',
}
