export enum QuestionFormat {
  FORCED_CHOICE_PAIR = 'FORCED_CHOICE_PAIR',
  FORCED_CHOICE_GROUP = 'FORCED_CHOICE_GROUP',
  MULTIPLE_CHOICE_ABC = 'MULTIPLE_CHOICE_ABC',
  PAIR_DISTRIBUTION = 'PAIR_DISTRIBUTION',
}
